import { spawn } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import express from 'express';
import dotenv from 'dotenv';

dotenv.config({ path: path.resolve('.env.local') });
dotenv.config({ path: path.resolve('.env') });

type Word = { id: string; text: string; start: number; end: number };
type KeepRange = { startWordId: string; endWordId: string; reason?: string };
type MediaProfile = { duration: number; size: number; width?: number; height?: number; videoCodec?: string; audioCodec?: string; pixelFormat?: string; colorTransfer?: string; colorPrimaries?: string; colorSpace?: string; hdr: boolean };
type Project = { id: string; sourcePath: string; workDir: string; sourceName: string; proxyPath?: string; audioPath?: string; transcript?: { text: string; words: Word[] }; edl?: { keepRanges: KeepRange[]; notes?: string[] }; media: MediaProfile };
type LocalSettings = { elevenLabsApiKey?: string; codexBin?: string; ffmpegBin?: string; ffprobeBin?: string; projectsDir?: string };

const CONFIG_DIR = path.join(os.homedir(), '.video-cleaner');
const CONFIG_PATH = path.join(CONFIG_DIR, 'config.json');
const app = express();
const projects = new Map<string, Project>();
let localSettings: LocalSettings = {};
app.use(express.json({ limit: '1mb' }));

const EDL_SCHEMA = { type: 'object', additionalProperties: false, required: ['keepRanges', 'notes'], properties: { keepRanges: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['startWordId', 'endWordId', 'reason'], properties: { startWordId: { type: 'string' }, endWordId: { type: 'string' }, reason: { type: 'string' } } } }, notes: { type: 'array', items: { type: 'string' } } } };

async function run(command: string, args: string[], stdin?: string, timeoutMs = 0) {
  return new Promise<{ stdout: string; stderr: string }>((resolve, reject) => {
    const child = spawn(command, args, { shell: false, windowsHide: true });
    let stdout = ''; let stderr = ''; let timer: NodeJS.Timeout | undefined;
    if (timeoutMs > 0) timer = setTimeout(() => { child.kill('SIGTERM'); reject(new Error(`${command} timed out`)); }, timeoutMs);
    child.stdout.on('data', (chunk) => (stdout += chunk.toString()));
    child.stderr.on('data', (chunk) => (stderr += chunk.toString()));
    child.on('error', (error) => { if (timer) clearTimeout(timer); reject(error); });
    child.on('close', (code) => { if (timer) clearTimeout(timer); if (code === 0) resolve({ stdout, stderr }); else reject(new Error(`${command} failed (${code})\n${stderr || stdout}`)); });
    child.stdin.end(stdin ?? '');
  });
}

async function loadSettings() { try { localSettings = JSON.parse(await fs.readFile(CONFIG_PATH, 'utf8')) as LocalSettings; } catch { localSettings = {}; } }
async function saveSettings() { await fs.mkdir(CONFIG_DIR, { recursive: true }); await fs.writeFile(CONFIG_PATH, JSON.stringify(localSettings, null, 2), { mode: 0o600 }); }
async function detectBinary(name: string) { try { const command = process.platform === 'win32' ? 'where' : 'which'; const { stdout } = await run(command, [name], undefined, 3000); return stdout.split(/\r?\n/).map((line) => line.trim()).find(Boolean) ?? ''; } catch { return ''; } }
async function resolvedSettings() {
  const codexOverride = localSettings.codexBin || process.env.CODEX_BIN || '';
  const ffmpegOverride = localSettings.ffmpegBin || process.env.FFMPEG_BIN || '';
  const ffprobeOverride = localSettings.ffprobeBin || process.env.FFPROBE_BIN || '';
  return { elevenLabsApiKey: localSettings.elevenLabsApiKey || process.env.ELEVENLABS_API_KEY || '', codexBin: codexOverride || await detectBinary('codex'), ffmpegBin: ffmpegOverride || await detectBinary('ffmpeg'), ffprobeBin: ffprobeOverride || await detectBinary('ffprobe'), projectsDir: localSettings.projectsDir || process.env.PROJECTS_DIR || path.join(os.homedir(), 'VideoCleaner', 'projects') };
}
async function canRun(binary: string, args: string[]) { if (!binary) return false; try { await run(binary, args, undefined, 5000); return true; } catch { return false; } }
async function systemStatus() { const settings = await resolvedSettings(); const [codexInstalled, ffmpegInstalled, ffprobeInstalled] = await Promise.all([canRun(settings.codexBin, ['--version']), canRun(settings.ffmpegBin, ['-version']), canRun(settings.ffprobeBin, ['-version'])]); const codexAuthenticated = codexInstalled ? await canRun(settings.codexBin, ['login', 'status']) : false; return { codex: { installed: codexInstalled, authenticated: codexAuthenticated, path: settings.codexBin || null }, ffmpeg: { installed: ffmpegInstalled, path: settings.ffmpegBin || null }, ffprobe: { installed: ffprobeInstalled, path: settings.ffprobeBin || null }, elevenLabs: { configured: Boolean(settings.elevenLabsApiKey) }, projectsDir: settings.projectsDir }; }

async function pickNativeFile() {
  if (process.platform === 'darwin') { const { stdout } = await run('osascript', ['-e', 'POSIX path of (choose file with prompt "Choose a talking-head video")']); return stdout.trim(); }
  if (process.platform === 'win32') { const script = ['Add-Type -AssemblyName System.Windows.Forms;', '$d = New-Object System.Windows.Forms.OpenFileDialog;', '$d.Filter = "Video files|*.mov;*.mp4;*.m4v;*.webm|All files|*.*";', 'if ($d.ShowDialog() -eq "OK") { Write-Output $d.FileName }'].join(' '); const { stdout } = await run('powershell', ['-NoProfile', '-Command', script]); return stdout.trim(); }
  try { const { stdout } = await run('zenity', ['--file-selection', '--title=Choose a talking-head video', '--file-filter=Video | *.mov *.mp4 *.m4v *.webm']); return stdout.trim(); } catch { throw new Error('No supported native file picker found. Install zenity or use macOS/Windows.'); }
}
async function pickExportPath() {
  if (process.platform === 'darwin') { const { stdout } = await run('osascript', ['-e', 'POSIX path of (choose file name with prompt "Export cleaned video" default name "cleaned-video.mp4")']); return stdout.trim(); }
  if (process.platform === 'win32') { const script = ['Add-Type -AssemblyName System.Windows.Forms;', '$d = New-Object System.Windows.Forms.SaveFileDialog;', '$d.Filter = "MP4 video|*.mp4";', '$d.FileName = "cleaned-video.mp4";', 'if ($d.ShowDialog() -eq "OK") { Write-Output $d.FileName }'].join(' '); const { stdout } = await run('powershell', ['-NoProfile', '-Command', script]); return stdout.trim(); }
  try { const { stdout } = await run('zenity', ['--file-selection', '--save', '--confirm-overwrite', '--filename=cleaned-video.mp4']); return stdout.trim(); } catch { throw new Error('No supported native save dialog found.'); }
}
async function probe(sourcePath: string): Promise<MediaProfile> { const settings = await resolvedSettings(); if (!settings.ffprobeBin) throw new Error('ffprobe was not found. Configure FFPROBE_BIN or install FFmpeg.'); const { stdout } = await run(settings.ffprobeBin, ['-v', 'error', '-show_streams', '-show_format', '-of', 'json', sourcePath]); const data = JSON.parse(stdout); const video = data.streams?.find((stream: any) => stream.codec_type === 'video') ?? {}; const audio = data.streams?.find((stream: any) => stream.codec_type === 'audio') ?? {}; const hdr = ['smpte2084', 'arib-std-b67'].includes(video.color_transfer); return { duration: Number(data.format?.duration ?? video.duration ?? 0), size: Number(data.format?.size ?? 0), width: video.width, height: video.height, videoCodec: video.codec_name, audioCodec: audio.codec_name, pixelFormat: video.pix_fmt, colorTransfer: video.color_transfer, colorPrimaries: video.color_primaries, colorSpace: video.color_space, hdr }; }
function getProject(id: string) { const project = projects.get(id); if (!project) throw new Error('Project not found. Re-select the source video after restarting the local server.'); return project; }
async function saveProject(project: Project) { await fs.writeFile(path.join(project.workDir, 'project.json'), JSON.stringify(project, null, 2)); }
function serializeProject(project: Project) { return { id: project.id, sourceName: project.sourceName, media: project.media }; }
function validateEdl(words: Word[], raw: any) { const index = new Map(words.map((word, i) => [word.id, i])); let previousEnd = -1; const ranges: KeepRange[] = []; for (const range of raw.keepRanges ?? []) { const start = index.get(range.startWordId); const end = index.get(range.endWordId); if (start === undefined || end === undefined || start > end) throw new Error('Invalid EDL word range'); if (start <= previousEnd) throw new Error('EDL ranges overlap or are out of order'); previousEnd = end; ranges.push({ startWordId: range.startWordId, endWordId: range.endWordId, reason: range.reason ?? '' }); } if (!ranges.length) throw new Error('The edit removed the entire video'); return { keepRanges: ranges, notes: Array.isArray(raw.notes) ? raw.notes : [] }; }
function rangesToSeconds(project: Project) { const words = project.transcript!.words; const index = new Map(words.map((word, i) => [word.id, i])); const seconds = project.edl!.keepRanges.map((range) => { const startWord = words[index.get(range.startWordId)!]; const endWord = words[index.get(range.endWordId)!]; return { start: Math.max(0, startWord.start - 0.08), end: Math.min(project.media.duration || Number.POSITIVE_INFINITY, endWord.end + 0.12) }; }); const merged: { start: number; end: number }[] = []; for (const segment of seconds) { const previous = merged.at(-1); if (previous && segment.start - previous.end < 0.2) previous.end = Math.max(previous.end, segment.end); else merged.push({ ...segment }); } return merged; }
function route(handler: (req: express.Request, res: express.Response) => Promise<void>) { return (req: express.Request, res: express.Response) => { handler(req, res).catch((error) => res.status(500).json({ error: error instanceof Error ? error.message : String(error) })); }; }

app.get('/api/system/status', route(async (_req, res) => { res.json(await systemStatus()); }));
app.get('/api/settings', route(async (_req, res) => { const status = await systemStatus(); res.json({ ...status, overrides: { codexBin: localSettings.codexBin ?? '', ffmpegBin: localSettings.ffmpegBin ?? '', ffprobeBin: localSettings.ffprobeBin ?? '', projectsDir: localSettings.projectsDir ?? '' } }); }));
app.put('/api/settings', route(async (req, res) => { const body = req.body ?? {}; if (typeof body.elevenLabsApiKey === 'string' && body.elevenLabsApiKey.trim()) localSettings.elevenLabsApiKey = body.elevenLabsApiKey.trim(); for (const key of ['codexBin', 'ffmpegBin', 'ffprobeBin', 'projectsDir'] as const) if (typeof body[key] === 'string') localSettings[key] = body[key].trim() || undefined; await saveSettings(); res.json(await systemStatus()); }));
app.post('/api/projects/select', route(async (_req, res) => { const sourcePath = await pickNativeFile(); if (!sourcePath) return void res.status(400).json({ error: 'No video selected' }); const settings = await resolvedSettings(); const id = randomUUID(); const workDir = path.join(settings.projectsDir, id); await fs.mkdir(workDir, { recursive: true }); const project: Project = { id, sourcePath, sourceName: path.basename(sourcePath), workDir, media: await probe(sourcePath) }; projects.set(id, project); await saveProject(project); res.json(serializeProject(project)); }));
app.post('/api/projects/:id/prepare', route(async (req, res) => { const project = getProject(req.params.id); const settings = await resolvedSettings(); if (!settings.ffmpegBin) throw new Error('FFmpeg was not found. Configure FFMPEG_BIN or install FFmpeg.'); const audioPath = path.join(project.workDir, 'analysis.m4a'); const proxyPath = path.join(project.workDir, 'proxy.mp4'); const proxyEncoder = process.platform === 'darwin' ? ['-c:v', 'h264_videotoolbox', '-b:v', '2500k'] : ['-c:v', 'libx264', '-preset', 'veryfast', '-crf', '27']; await Promise.all([run(settings.ffmpegBin, ['-y', '-i', project.sourcePath, '-map', '0:a:0', '-vn', '-ac', '1', '-ar', '16000', '-c:a', 'aac', '-b:a', '48k', audioPath]), run(settings.ffmpegBin, ['-y', '-i', project.sourcePath, '-vf', 'scale=-2:720', ...proxyEncoder, '-c:a', 'aac', '-b:a', '96k', '-movflags', '+faststart', proxyPath])]); project.audioPath = audioPath; project.proxyPath = proxyPath; await saveProject(project); res.json({ proxyUrl: `/api/projects/${project.id}/proxy` }); }));
app.get('/api/projects/:id/proxy', route(async (req, res) => { const project = getProject(req.params.id); if (!project.proxyPath) throw new Error('Proxy has not been generated yet'); res.sendFile(project.proxyPath); }));
app.post('/api/projects/:id/transcribe', route(async (req, res) => { const project = getProject(req.params.id); const settings = await resolvedSettings(); if (!project.audioPath) throw new Error('Prepare the project first'); if (!settings.elevenLabsApiKey) throw new Error('ElevenLabs API key is not configured'); const bytes = await fs.readFile(project.audioPath); const form = new FormData(); form.append('model_id', 'scribe_v2'); form.append('timestamps_granularity', 'word'); form.append('file', new Blob([bytes]), 'analysis.m4a'); const response = await fetch('https://api.elevenlabs.io/v1/speech-to-text', { method: 'POST', headers: { 'xi-api-key': settings.elevenLabsApiKey }, body: form }); if (!response.ok) throw new Error(`ElevenLabs failed: ${response.status} ${await response.text()}`); const raw: any = await response.json(); const words: Word[] = (raw.words ?? []).filter((word: any) => word.type === 'word' && Number.isFinite(word.start) && Number.isFinite(word.end)).map((word: any, index: number) => ({ id: `w${String(index + 1).padStart(6, '0')}`, text: word.text, start: word.start, end: word.end })); if (!words.length) throw new Error('No timestamped words returned by ElevenLabs'); project.transcript = { text: raw.text ?? words.map((word) => word.text).join(' '), words }; project.edl = { keepRanges: [{ startWordId: words[0].id, endWordId: words.at(-1)!.id, reason: 'Original recording' }], notes: [] }; await Promise.all([fs.writeFile(path.join(project.workDir, 'transcript.json'), JSON.stringify(project.transcript, null, 2)), saveProject(project)]); res.json({ transcript: project.transcript, edl: project.edl }); }));
app.post('/api/projects/:id/clean', route(async (req, res) => { const project = getProject(req.params.id); const settings = await resolvedSettings(); const intensity = ['light', 'balanced', 'aggressive'].includes(req.body?.intensity) ? req.body.intensity : 'balanced'; if (!project.transcript) throw new Error('Transcribe the project first'); if (!settings.codexBin) throw new Error('Codex CLI was not found. Configure CODEX_BIN or install Codex.'); const schemaPath = path.join(project.workDir, 'edl.schema.json'); const outputPath = path.join(project.workDir, 'codex-edl.json'); await fs.writeFile(schemaPath, JSON.stringify(EDL_SCHEMA, null, 2)); const transcript = project.transcript.words.map((word) => `[${word.id} ${word.start.toFixed(3)}-${word.end.toFixed(3)}] ${word.text}`).join('\n'); const prompt = `You are a professional talking-head dialogue cleaning editor.\n\nThis is DELETE-ONLY editing. Never invent, paraphrase, replace, reorder, or combine spoken words. Keep source chronology. Return only ranges of ORIGINAL words to keep.\n\nCleanup intensity: ${intensity}.\nLight: remove clear fillers, abandoned false starts, duplicate takes, and excessive dead space only.\nBalanced: also remove low-value repetition and concise tangents while preserving natural speech.\nAggressive: optimize pacing strongly, but preserve meaning and grammatical continuity.\n\nPrefer natural cut points. Do not remove a word merely because it is imperfect if the resulting edit sounds unnatural.\n\nSOURCE WORDS:\n${transcript}`; await run(settings.codexBin, ['exec', '--ephemeral', '--output-schema', schemaPath, '--output-last-message', outputPath, '-'], prompt); const raw = JSON.parse(await fs.readFile(outputPath, 'utf8')); project.edl = validateEdl(project.transcript.words, raw); await Promise.all([fs.writeFile(path.join(project.workDir, 'edl.json'), JSON.stringify(project.edl, null, 2)), saveProject(project)]); res.json(project.edl); }));
app.put('/api/projects/:id/edl', route(async (req, res) => { const project = getProject(req.params.id); if (!project.transcript) throw new Error('Missing transcript'); project.edl = validateEdl(project.transcript.words, { keepRanges: req.body?.keepRanges, notes: ['Manually adjusted'] }); await Promise.all([fs.writeFile(path.join(project.workDir, 'edl.json'), JSON.stringify(project.edl, null, 2)), saveProject(project)]); res.json(project.edl); }));
app.post('/api/projects/:id/export', route(async (req, res) => { const project = getProject(req.params.id); const settings = await resolvedSettings(); if (!project.transcript || !project.edl) throw new Error('Missing transcript or edit decision list'); if (!settings.ffmpegBin) throw new Error('FFmpeg was not found'); const outputPath = await pickExportPath(); if (!outputPath) return void res.status(400).json({ error: 'Export cancelled' }); const mode = req.body?.mode === 'quality' ? 'quality' : 'fast'; const segments = rangesToSeconds(project); const chains: string[] = []; const refs: string[] = []; segments.forEach((segment, index) => { chains.push(`[0:v]trim=start=${segment.start}:end=${segment.end},setpts=PTS-STARTPTS[v${index}]`); chains.push(`[0:a]atrim=start=${segment.start}:end=${segment.end},asetpts=PTS-STARTPTS[a${index}]`); refs.push(`[v${index}][a${index}]`); }); chains.push(`${refs.join('')}concat=n=${segments.length}:v=1:a=1[vout][aout]`); let videoArgs: string[]; if (project.media.hdr) videoArgs = mode === 'fast' && process.platform === 'darwin' ? ['-c:v', 'hevc_videotoolbox', '-b:v', '45M', '-tag:v', 'hvc1'] : ['-c:v', 'libx265', '-preset', 'slow', '-crf', '14', '-pix_fmt', 'yuv420p10le', '-tag:v', 'hvc1']; else videoArgs = mode === 'fast' && process.platform === 'darwin' ? ['-c:v', 'h264_videotoolbox', '-b:v', '35M'] : mode === 'fast' ? ['-c:v', 'libx264', '-preset', 'veryfast', '-crf', '18'] : ['-c:v', 'libx264', '-preset', 'slow', '-crf', '16']; const colorArgs: string[] = []; if (project.media.colorPrimaries) colorArgs.push('-color_primaries', project.media.colorPrimaries); if (project.media.colorTransfer) colorArgs.push('-color_trc', project.media.colorTransfer); if (project.media.colorSpace) colorArgs.push('-colorspace', project.media.colorSpace); await run(settings.ffmpegBin, ['-y', '-i', project.sourcePath, '-filter_complex', chains.join(';'), '-map', '[vout]', '-map', '[aout]', ...videoArgs, ...colorArgs, '-c:a', 'aac', '-b:a', '256k', '-movflags', '+faststart', outputPath]); res.json({ outputPath }); }));

const PORT = Number(process.env.PORT || 3001);
await loadSettings();
if (process.env.NODE_ENV === 'production') { const distDir = path.resolve('dist'); app.use(express.static(distDir)); app.get('*', (_req, res) => res.sendFile(path.join(distDir, 'index.html'))); }
app.listen(PORT, '127.0.0.1', () => console.log(`Video Cleaner local server: http://127.0.0.1:${PORT}`));
